### ISSUE TITLE
Better CSS code in the mobile view for the com_search and com_finder

### ISSUE THREAD

**Issue by dziudek** [GavickPro/Music-Free-Responsive-Joomla-Template#14]
To add in the mobile.css file:

``` css
/* Fix for the search */
fieldset.word #search-searchword,
fieldset.word .inputbox {
    width: 50%;
}
fieldset.phrases .ordering-box,
fieldset.only input[type="checkbox"],
fieldset.phrases input[type="radio"] {
    clear: both;
}
```

@bkrztuk - please also try to add it in the Fashion template.
