### ISSUE TITLE
Disable image hover animation

### ISSUE THREAD

**Issue by coffeemon** [GavickPro/Music-Free-Responsive-Joomla-Template#150]
Hello,

Is there any way I can disable the hover animation on all the images? I tried going to each module > additional settings > animation > disable, but the animation is still there! Help? 

![screen shot 2013-08-02 at 12 14 58 am](https://f.cloud.github.com/assets/5139942/895106/8d3d6d5a-fac5-11e2-8ea4-cf570a7dbefe.png)

I just want the images to stay put. 

I hope someone can help me out. Thanks in advance!

**Comment by bkrztuk** [comment]
Please open file template/css/gk.stuff.css and remove this code : 

``` css
.nspArt .nspImageWrapper:hover img {
    -webkit-transform: scale(1.2) rotate(-7deg);
    -moz-transform: scale(1.2) rotate(-7deg);
    -ms-transform: scale(1.2) rotate(-7deg);
    -o-transform: scale(1.2) rotate(-7deg);
    transform: scale(1.2) rotate(-7deg);
}
```
