### ISSUE TITLE
Fixed Menu

### ISSUE THREAD

**Issue by newbziex** [GavickPro/Music-Free-Responsive-Joomla-Template#154]
Hello.

How can I make the top menu to move with page like footer? I think it's question of changing a few lines in the *.css, but I don't know where.

Thanks in advance.

**Comment by bkrztuk** [comment]
Please try to use this code in _override.css_ file and make sure that option 'Use override CSS' is enabled in template settings : 

``` css
#gkPageTop {position: fixed; z-index: 100; margin-top: 28px}
```
