### ISSUE TITLE
Facebook Overlay

### ISSUE THREAD

**Issue by ManfredHeindl** [GavickPro/Music-Free-Responsive-Joomla-Template#182]
there is a problem with the facebook overlay on K2 item page.
- hide the comment function
- hide author options

the overlay cut off

![facebook-bug](https://f.cloud.github.com/assets/2233128/1899288/e8a574aa-7c37-11e3-93d8-8df06ef8eec0.PNG)

**Comment by bkrztuk** [comment]
@ManfredHeindl please try with this code : 

``` css
#gkPage > #gkContent { overflow: visisble }
```

Please let me know about results.
